name: CMake Build Matrix

on: [push, pull_request]

jobs:
  build_and_test:
    name: "${{ matrix.compiler }} / ${{ matrix.buildType }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - gcc-11
          - gcc-12
          - llvm-14
          - llvm-15
        buildType:
          - Release
          - RelWithDebug
          - Debug
          - Asan
          - AsanDebug
          - Tsan

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -yq libgtest-dev libgmock-dev libbenchmark-dev cmake ninja-build
    - name: Setup Compiler
      uses: aminya/setup-cpp@v1
      with:
        compiler: ${{ matrix.compiler }}
        cmake: true
        ninja: true
      
    - name: Configure
      run: |
        if [ -d "build" ]; then rm -rf ./build; fi
        mkdir -p build
        cd build
        cmake -GNinja ../ -DCMAKE_VERBOSE_MAKEFILE=ON -DCXXITER_WITH_TESTS=ON -DCMAKE_BUILD_TYPE=${{ matrix.buildType }}
    
    - name: Build
      run: |
        cd build/
        cmake --build .
        
    - name: Test
      run: |
        cd build/
        export ASAN_OPTIONS=detect_leaks=0
        export TSAN_OPTIONS=ignore_noninstrumented_modules=1
        ctest -j4 --output-on-failure
